# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YDOpenHardwareSimple' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

platform :ios, '7.0'

  pod 'BabyBluetooth', '~> 0.7.0'
  pod 'WebViewJavascriptBridge', '~> 6.0.2'
  pod 'Masonry', '~> 1.0.2'
  pod 'FMDB', '~> 2.7.2'
  # Pods for YDOpenHardwareSimple

  target 'YDOpenHardwareSimpleTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'YDOpenHardwareSimpleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
